const {
  PORT = 3000, BASE_HOST, NODE_ENV, BASE_USER, BASE_NAME, BASE_PASSWORD, ALLOWED_CORS,
} = process.env;

module.exports = {
  PORT, BASE_HOST, NODE_ENV, BASE_USER, BASE_NAME, BASE_PASSWORD, ALLOWED_CORS,
};
